name: "Víctor Fernández"
desciption: "Designer and front-end developer"
greeting: "Víctor Fernández. <span>Designer and front-end developer.</span>"
email: victor@auth0.com
markdown: kramdown
permalink: /:year/:title
highlighter: true
exclude: [node_modules, Gruntfile.js, Gemfile, Gemfile.lock, config.ru, package.json, README.md]
destination: public

navigation:
- text: Current Projects
  url: '#projects'
  icon: clock
- text: Get in touch
  url: '#contact'
  icon: mail
- text: About me
  url: '#about-me'
  icon: user

social:
- name: Twitter
  url: http://twitter.com/vctrfrnndz
- name: Github
  url: http://github.com/vctrfrnndz
- name: Dribbble
  url: http://dribbble.com/vctrfrnndz
- name: Medium
  url: http://medium.com/@vctrfrnndz

projects:
- name: jQuery Accordion
  description: "Generates accordions powered by CSS transitions to animate opening/closing with a fallback to jQuery's animate when CSS transitions are not supported. It takes little configuration or code to use it on your project."
  play_link: http://vctrfrnndz.github.io/jquery-accordion/
  github_link: https://github.com/vctrfrnndz/jquery-accordion
  image: http://f.cl.ly/items/1S091P2A0T1A2p3F1y0n/accordion.png
- name: JSblackjack
  description: "A fully JS blackjack game. Because the world needed another. Very few images involved, just icon font trickery."
  play_link: http://vctrfrnndz.github.io/JSblackjack/
  github_link: https://github.com/vctrfrnndz/JSblackjack/
- name: Kick
  description: "Kick is a collection of useful LESS mixins for use on any project."
  github_link: https://github.com/vctrfrnndz/Kick/
  download_link: https://raw.github.com/vctrfrnndz/kick/master/less/kick.less
- name: Icomin
  description: "Icomin is a minimal set of icons for general purpose. Includes both individual SVG's and icon font."
  github_link: https://github.com/vctrfrnndz/Icomin/
  download_link: https://github.com/vctrfrnndz/Icomin/archive/v0.1.tar.gz
  image: http://cl.ly/image/3V383p2w2m0X/preview.jpg
